### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by jimisens** [aurelia-plugins/aurelia-plugins-google-places-autocomplete#1]
Hello, 
I just install and configure your plugin like in the instructions and i have the following error 
Unhandled rejection ReferenceError: regeneratorRuntime is not defined

I'm using Aurelia Cli, Node v 6.9.1 and NPM 3.10.8 
I think a library is missing perhaps ? 
Thank you very much

**I'm submitting a bug report**
**I'm submitting a feature request**

* **Framework Version:**
major.minor.patch-pre

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x|Linux (distro)|Windows [7|8|8.1|10]

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
JSPM 0.16.32 | webpack 2.1.0-beta.17

* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView

* **Language:**
all | TypeScript X.X | ESNext

**Current behavior:**

**Expected/desired behavior:**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

**Comment by bartlenaerts** [comment]
Hi @jimisens,

I found some information here about the fact that the plugin is using async/await functionality, which could have problems with the specific transpiler you're using. Can you have a look at these threads:
https://github.com/aurelia/cli/issues/291
http://stackoverflow.com/questions/33527653/babel-6-regeneratorruntime-is-not-defined-with-async-await

Please let me know if it helped you.

Thanks,
Bart

**Comment by jmberon** [comment]
Hi @bartlenaerts,
Experiencing the same problem. According to the Stackoverflow thread you shared, this plugin needs to install babel-plugin-transform-runtime in order to fix those async/await. Do you know how to actually build the plugin once cloned ? Any pointers would be appreciated. Thanks.

**Comment by threeaccents** [comment]
I'm having the same issue.

**Comment by bartlenaerts** [comment]
Hi,

please add `node_modules/babel-polyfill/dist/polyfill.min.js` to the prepend list in `aurelia.json`. Do not forgot to add `babel-polyfill` to the dependencies in `package.json`.

Greetz, Bart
