### ISSUE TITLE
<strong> tags are injecting into the innerHTML incorrectly

### ISSUE THREAD

**Issue by nathanchase** [aurelia-plugins/aurelia-plugins-google-places-autocomplete#4]
I've noticed that there's something wrong with the way the innerHTML is being created on line 18 of aurelia-plugins-google-places-autocomplete-converter.js in the HighlightValueConverter method:

```
HighlightValueConverter.prototype.toView = function toView(array) {
    array.forEach(function (item) {
      if (!item.matched_substrings || !item.matched_substrings.length) return;
      item.innerHTML = item.description;
      for (var i = 0, j = item.matched_substrings.length; i < j; i++) {
        console.log(`item.matched_substrings: ${item.matched_substrings}`);
        var length = item.matched_substrings[i].length;
        console.log(`length: ${length}`);
        var offset = item.matched_substrings[i].offset + i * 17;
        console.log(`offset: ${offset}`);
        item.innerHTML = [item.innerHTML.slice(0, offset), '<strong>', item.innerHTML.slice(offset, length), '</strong>', item.innerHTML.slice(length)].join('');
        console.log(`item.innerHTML: ${item.innerHTML}`);
      }
    });
    return array;
  };
```
It seems to work fine when there's just a single object, but when there's more than one, the `<strong>` tags seem to somehow get pushed into the innerHTML incorrectly and are appearing in the actual string in the input field.

Here's a screenshot I took trying to debug it:
![capture2](https://cloud.githubusercontent.com/assets/5963574/24711135/156f2502-19ed-11e7-94ae-f612becac107.PNG)

I'm not sure exactly how to fix this, but I imagine it's a matter of making sure that the `'length` and `offset` variables are taking into account the number of objects in the string.

Thanks!

**Comment by ne0guille** [comment]
have u change the code? mine doesn't show any style nor icons on the elemtns

**Comment by nathanchase** [comment]
That styling has nothing to do with the string passed into the element. It's just classes surrounding the element.

**Comment by bartlenaerts** [comment]
Fixed!

**Comment by nathanchase** [comment]
Excellent! Thanks so much for fixing this!
