### ISSUE TITLE
ReferenceError: event is not defined

### ISSUE THREAD

**Issue by laura-richer** [aurelia-plugins/aurelia-plugins-google-places-autocomplete#5]
I am getting a js error in Firefox (working fine on every other browser) flagging up in the aurelia-plugins-google-places-autocomplete-element.js...

ReferenceError: event is not defined

Firefox error says the issue is with the _dispatchEvent function around line 245

  
<img width="1238" alt="screen shot 2018-01-08 at 10 34 54" src="https://user-images.githubusercontent.com/28528405/34667134-97494150-f45f-11e7-8cd1-87f29b37cee6.png">

**Comment by bartlenaerts** [comment]
Sorry, finally fixed... Check version v2.5.6
